HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I'm a **Software Engineer** from Taiwan, passionate about **Computer Vision**, **Machine Learning**, **Signal Processing**, and Visual related Technologies. With solid experience in machine learning, software systems development, and **full-stack web applications**.

    I recently graduated from **The Hong Kong University of Science and Technology** with a BEng in **Computer Engineering** and a minor in **Big Data Technology**.
    Currently, I work as a **Research Assistant** at **Academia Sinica** in Institution of Statistics, where I contribute to cutting-edge research projects in **Smart Health Project** and **AI-driven Analysis**.

    Feel free to connect and get in touch with me :)

DOING:
  enabled: true
  label: "What I'm doing | Interested in"
  items:
    - title: "Computer Vision"
      icon: "tv"
      description: "Developing real-time object detection and tracking systems with YOLO; Researching Agentic AI for advanced medical image analysis."
    - title: "Machine Learning"
      icon: "code-slash"
      description: "Investigating state-of-the-art NLP and deep learning architectures, including transformer-based models for practical applications."
    # - title: "Computer Architecture"
    #   icon: "terminal"
    #   description: "Optimizing GPU-accelerated parallel-compute frameworks and exploring hardware-software co-design for high-performance systems."
    # - title: "Computer Graphics"
    #   icon: "film"
    #   description: "Studying graphics pipelines at both software and hardware levels, from real-time shader development to GPU rendering optimization."
    - title: "System Development"
      icon: "cog"
      description: "Building efficient and scalable software systems using Python and JavaScript, with a focus on performance optimization, data transmission and seamless integration."
    - title: "Web Development"
      icon: "globe"
      description: "Building full-stack web applications using modern frameworks like React, Node.js, and FastAPI for seamless user experiences."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/flash.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/people.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members, also experienced in leading teams."
    - title: "Problem Solving"
      icon: "config/assets/icons/setting.svg"
      description: "I am creative and efficient in painpointing the issue and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/chatbubbles.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Technical Skills"
  sections:
    - title: "Programming Languages"
      items:
        - title: "Python"
          icon: "config/assets/icons/python.svg"
        - title: "C++"
          icon: "config/assets/icons/cpp.svg"
        - title: "C"
          icon: "config/assets/icons/c.svg"
        - title: "TypeScript"
          icon: "config/assets/icons/typescript.svg"
        - title: "JavaScript"
          icon: "config/assets/icons/javascript.svg"
        - title: "MATLAB"
          icon: "config/assets/icons/matlab.svg"
        - title: "MIPS Assembly"
          icon: "config/assets/icons/chip.svg"
    
    - title: "Machine Learning & Data Science"
      items:
        - title: "PyTorch"
          icon: "config/assets/icons/pytorch.svg"
        - title: "TensorFlow"
          icon: "config/assets/icons/tensorflow.svg"
        - title: "OpenCV"
          icon: "config/assets/icons/opencv.svg"
        - title: "Supervision"
          icon: "config/assets/icons/roboflow.svg"
        - title: "NumPy"
          icon: "config/assets/icons/numpy.svg"
        - title: "Pandas"
          icon: "config/assets/icons/pandas.svg"
        - title: "Scikit-learn"
          icon: "config/assets/icons/python.svg"
        - title: "Hugging Face Transformers"
          icon: "config/assets/icons/huggingface.svg"
        - title: "Matplotlib"
          icon: "config/assets/icons/matplotlib.svg"
        - title: "Seaborn"
          icon: "config/assets/icons/seaborn.svg"

    - title: "Big Data & Cloud Computing"
      items:
        - title: "Apache Spark"
          icon: "config/assets/icons/spark.svg"
        - title: "Apache Hadoop"
          icon: "config/assets/icons/hadoop.svg"
        - title: "Amazon EC2"
          icon: "config/assets/icons/aws.svg"
    
    - title: "Web Development & Databases"
      items:
        - title: "React"
          icon: "config/assets/icons/react.svg"
        - title: "Node.js"
          icon: "config/assets/icons/nodejs.svg"
        - title: "Streamlit"
          icon: "config/assets/icons/streamlit.svg"
        - title: "Redis"
          icon: "config/assets/icons/redis.svg"
        - title: "FastAPI"
          icon: "config/assets/icons/fastapi.svg"
        - title: "Flask"
          icon: "config/assets/icons/flask.svg"

    - title: "Parallel & Systems Programming"
      items:
        - title: "CUDA"
          icon: "config/assets/icons/cuda.svg"
        - title: "MPI"
          icon: "config/assets/icons/c.svg"
        - title: "Pthreads"
          icon: "config/assets/icons/c.svg"
        - title: "OpenMP"
          icon: "config/assets/icons/cpp.svg"
        - title: "OpenGL"
          icon: "config/assets/icons/opengl.svg"
    
    - title: "DevOps & Deployment Tools"
      items:
        - title: "Git"
          icon: "config/assets/icons/git.svg"
        - title: "Docker"
          icon: "config/assets/icons/docker.svg"
        - title: "Kubernetes"
          icon: "config/assets/icons/kubernetes.svg"
        - title: "Linux"
          icon: "config/assets/icons/linux.svg"
    
    - title: "Design & Media"
      items:
        - title: "Adobe Illustrator"
          icon: "config/assets/icons/ai.svg"
        - title: "Final Cut Pro"
          icon: "config/assets/icons/finalcut.svg"

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Mandarin"
      proficiency: "100%"
    - language: "English"
      proficiency: "80%"
    - language: "Cantonese"
      proficiency: "30%"
    - language: "Korean"
      proficiency: "30%"

CERTIFICATES:
  enabled: true
  label: "Certificates"
  items:
    - title: "Hugging Face LLM"
      link: "https://cdn-uploads.huggingface.co/production/uploads/noauth/tEqA8uAEbMZnmd6Gycqyd.webp"
    - title: "Hugging Face AI Agent"
      link: "https://cas-bridge.xethub.hf.co/xet-bridge-us/67a47037749ea2c4b9fafd4b/818a97fbd1b1ed9e1bc3819c3e906410ee8ececb28e2a714f847cb1cd52f987b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20250927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250927T062455Z&X-Amz-Expires=3600&X-Amz-Signature=9711359f1cdbdfd9af24e207abcb7d5d94e49e58e31b937ddd8d26c70e4576fc&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%272025-09-18.png%3B+filename%3D%222025-09-18.png%22%3B&response-content-type=image%2Fpng&x-id=GetObject&Expires=1758957895&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1ODk1Nzg5NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82N2E0NzAzNzc0OWVhMmM0YjlmYWZkNGIvODE4YTk3ZmJkMWIxZWQ5ZTFiYzM4MTljM2U5MDY0MTBlZThlY2VjYjI4ZTJhNzE0Zjg0N2NiMWNkNTJmOTg3YioifV19&Signature=eLjjo4gjFArmIlRVWZ-qsV7E4PjrXzTOr0dC6MhlVi%7EvAmdPHnhkFmXlCA7%7EYTjUj5%7E-2z-BwRxi-TGJu8EDAGT2Lt8sT05my34q2QGpyXd-CslG7KkT05x7Yx5n3tCSm8ffCpbmLZyRDzwMh3O%7E9230Rl0M0kOI%7EckqhKwxoc3YwSeJjSf497l3EgUBxfXBAOi7ZKsT-mnWfpyjTXhsSkaTO9DS0Ad544JqTF8XKZI2hZSJweuFoqQo0nJKI%7EZ9L8G4LsLtcN9MVpAHPBNqGd9hXAE7yKBO6dQukmI-wvShX7q88qNCc%7EgMwcX1%7EClPUI9t%7E3KhNRDSCpPYamDdIg__&Key-Pair-Id=K2L8F4GPSG1IFC"
    - title: "Statistics Course"
      link: "https://coursera.org/share/6e370954ae0c8daa9178699be731b215"
    - title: "Algorithm Course"
      link: "#"
